name: Welcome The Refugees

google_analytics: UA-64329198-4
social_media_image: http://welcometherefugees.de/img/welcometherefugees.png
url: http://welcometherefugees.de

baseurl: "/"

markdown: redcarpet
highlighter: pygments
permalink: /:categories/:title/

sass:
  style: :compressed # You might prefer to minify using :compressed

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

exclude:
    - design
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      lang: de
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_posts/de"
    values:
      lang: de
      categories:
        - de
  -
    scope:
      path: "_posts/en"
    values:
      lang: en
      categories:
        - en
